travel:
  profile: E:/profile/
  copyrightYear: 2019
server:
  port: 8081
  servlet:
    context-path: /travelsocial
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30
  #数据源的基本信息
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/travel_social?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    druid:
      initialSize: 5
      minIdle: 10
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      #minEvictableIdleTimeMillis: 300000
      #maxEvictableIdleTimeMillis: 900000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  mvc:
    view:
      prefix: /
      suffix: .html

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3000

mybatis:
  mapperLocations: classpath*:mapper/*.xml
  typeAliasesPackage: com.wmj.design.travelsocial
  configLocation: classpath:mybatis/mybatis-config.xml

commonStr:
  login:
    pre: ts-
  smsCode:
    pre: register-sms-code-


