server:
  port: 8080
  servlet:
    context-path: /travelsocial
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30
  #数据源的基本信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel_social?characterEncoding=UTF-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  mvc:
    view:
      prefix: /
      suffix: .html


  #spring.thymeleaf.suffix=.html
  #spring.thymeleaf.servlet.content-type=text/html
  #spring.thymeleaf.enabled=true
  #spring.thymeleaf.encoding=UTF-8
  #spring.thymeleaf.mode=HTML
  #spring.thymeleaf.check-template-location=true
  #开放式关闭缓存，不然没法看到实时页面
  #mybatis中mapper文件的路径

mybatis:
  mapperLocations: classpath*:mapper/*.xml
  typeAliasesPackage: com.wmj.design.travelsocial.dao
  #configLocation: classpath:mybatis/mybatis-config.xml

  #起别名。可省略写mybatis的xml中的resultType的全路径
  #mybatis.type-aliases-package=com.test.springboot.ssm.pojo
  #springMVC中的视图信息，响应前缀
#spring.mvc.view.prefix=/
  # 响应页面默认后缀
#spring.mvc.view.suffix=.html
  #DispatcherServlet中响应的url-pattern
#server.sevlet-path=*.html
  #server.context-path=/boot
  #logging.level.root=debug
#logging.level.com.test.springboot.ssm.dao=trace
